### ISSUE TITLE
Feature suggestion: VRAM optimization

### ISSUE THREAD

**Issue by playdasegunda** [kpthedev/stable-karlo#5]
I would like to know if it is possible to optimize karlo to be compatible with a 6 GB VRAM GPU. I installed the repository when it was released, but I had VRAM problems due to my 6 GB GPU. I now realize that a 7 GB GPU may be compatible. I would like to know if it is possible to further optimize the project to improve compatibility with 6 GB VRAM GPUs. I appreciate your response in advance.

**Comment by kpthedev** [comment]
Unfortunately, 7GB is the best that it can manage right now. I'm currently experimenting with different ways to lower the VRAM requirement and will add them to the repo when I get them working.

**Comment by kpthedev** [comment]
Google Colab support has been added! This is currently the best solution for users with less than 8GB of VRAM.
